
# generated by: jx gitops variables
export APP_NAME="nodey400"
export BRANCH_NAME="master"
export BUILD_NUMBER="1601290524079"
export DOCKER_REGISTRY="gcr.io"
export DOCKER_REGISTRY_ORG="jenkins-x-labs-bdd"
export JX_CHART_REPOSITORY="http://jenkins-x-chartmuseum:8080"
export PIPELINE_KIND="release"
export REPO_NAME="nodey400"
export REPO_OWNER="jstrachan"



# generated by: jx gitops variables
export APP_NAME="nodey400"
export BRANCH_NAME="master"
export BUILD_NUMBER="1601292343090"
export DOCKER_REGISTRY="gcr.io"
export DOCKER_REGISTRY_ORG="jenkins-x-labs-bdd"
export JX_CHART_REPOSITORY="http://jenkins-x-chartmuseum:8080"
export PIPELINE_KIND="release"
export REPO_NAME="nodey400"
export REPO_OWNER="jstrachan"
